/* DATA: logical tables ready to move to a database later. */
const demoDatabase = {
  people:[
    {id:'person_1',name:'Ahmet Yılmaz',birthDate:'1975-03-12',deathDate:null,occupation:'Mühendis',description:'Tamamen örnek/demo kişi kaydıdır.',tags:['demo'],sources:['source_1'],x:20,y:26},
    {id:'person_2',name:'Mehmet Kaya',birthDate:'1978-08-05',deathDate:null,occupation:'Danışman',description:'Tamamen örnek/demo kişi kaydıdır.',tags:['demo'],sources:[],x:75,y:28},
    {id:'person_3',name:'Ayşe Demir',birthDate:'1984-11-19',deathDate:null,occupation:'Araştırmacı',description:'Tamamen örnek/demo kişi kaydıdır.',tags:['demo'],sources:[],x:65,y:70},
    {id:'person_4',name:'Ali Can',birthDate:'1988-02-14',deathDate:null,occupation:'Tasarımcı',description:'Tamamen örnek/demo kişi kaydıdır.',tags:['demo'],sources:[],x:34,y:74}],
  events:[{id:'event_1',name:'Toplantı A',startDate:'2020-05-12',endDate:'2020-05-12',locationId:'location_1',type:'toplantı',description:'Demo amaçlı toplantı.',sources:['source_1'],x:38,y:48},{id:'event_2',name:'Toplantı B',startDate:'2022-09-08',endDate:'2022-09-08',locationId:'location_2',type:'forum',description:'Demo amaçlı forum.',sources:[],x:70,y:51},{id:'event_3',name:'Olay C',startDate:'2024-02-10',endDate:'2024-02-10',locationId:'location_1',type:'atölye',description:'Demo amaçlı atölye.',sources:[],x:49,y:84}],
  organizations:[{id:'org_1',name:'ABC Kurumu',founded:'2000-01-01',closed:null,description:'Demo kurumu.',locationId:'location_1',sources:[],x:55,y:35},{id:'org_2',name:'XYZ Kurumu',founded:'2014-01-01',closed:null,description:'Demo kurumu.',locationId:'location_2',sources:[],x:83,y:66}],
  locations:[{id:'location_1',name:'Ankara',country:'Türkiye',latitude:39.9334,longitude:32.8597,description:'Demo yer kaydı.',x:15,y:63},{id:'location_2',name:'İstanbul',country:'Türkiye',latitude:41.0082,longitude:28.9784,description:'Demo yer kaydı.',x:87,y:45}],
  sources:[{id:'source_1',title:'Örnek Belge',date:'2020-05-13',type:'belge',url:'',description:'Demo kaynak belgesi.',x:28,y:88}],
  relationships:[
    {id:'rel_1',source:'person_1',target:'event_1',type:'katıldı',startDate:'2020-05-12',endDate:null,description:'Katılımcı olarak bulundu.',confidence:'high',sources:['source_1'],directed:true},
    {id:'rel_2',source:'event_1',target:'location_1',type:'gerçekleşti',startDate:'2020-05-12',endDate:null,description:'Toplantı Ankara’da gerçekleşti.',confidence:'high',sources:[],directed:true},
    {id:'rel_3',source:'person_1',target:'person_2',type:'tanışıyor',startDate:'2020-05-12',endDate:null,description:'Toplantıda tanıştılar.',confidence:'medium',sources:[],directed:false},
    {id:'rel_4',source:'person_2',target:'org_1',type:'çalışıyor',startDate:'2021-01-01',endDate:null,description:'ABC Kurumu danışmanı.',confidence:'high',sources:[],directed:true},
    {id:'rel_5',source:'org_1',target:'event_2',type:'düzenledi',startDate:'2022-09-08',endDate:null,description:'Forum düzenleyicisi.',confidence:'high',sources:[],directed:true},
    {id:'rel_6',source:'person_3',target:'event_2',type:'katıldı',startDate:'2022-09-08',endDate:null,description:'Forum katılımcısı.',confidence:'high',sources:[],directed:true},
    {id:'rel_7',source:'person_3',target:'org_2',type:'çalışıyor',startDate:'2023-02-01',endDate:null,description:'XYZ Kurumu araştırmacısı.',confidence:'medium',sources:[],directed:true},
    {id:'rel_8',source:'org_2',target:'event_3',type:'organize etti',startDate:'2024-02-10',endDate:null,description:'Atölyeyi organize etti.',confidence:'high',sources:[],directed:true},
    {id:'rel_9',source:'person_4',target:'event_3',type:'katıldı',startDate:'2024-02-10',endDate:null,description:'Atölye katılımcısı.',confidence:'high',sources:[],directed:true},
    {id:'rel_10',source:'event_3',target:'location_1',type:'gerçekleşti',startDate:'2024-02-10',endDate:null,description:'Atölye Ankara’da gerçekleşti.',confidence:'high',sources:[],directed:true},
    {id:'rel_11',source:'event_1',target:'source_1',type:'kaynaklandı',startDate:'2020-05-13',endDate:null,description:'Belgeyle desteklenir.',confidence:'high',sources:['source_1'],directed:true}
  ]
};
let db=loadDatabase(), selectedId=null, pathIds=[], degree=1, animationYear=null, animationTimer=null;
const typeInfo={person:['Kişi','●','people'],event:['Olay','◆','events'],organization:['Kurum','■','organizations'],location:['Yer','▲','locations'],source:['Belge','▣','sources']};
const $=s=>document.querySelector(s); const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

// INITIALIZATION
document.addEventListener('DOMContentLoaded',()=>{bindEvents(); renderFilters(); renderPathOptions(); renderAll();});
function bindEvents(){ $('#search').addEventListener('input',renderSearch); $('#clear-filters').addEventListener('click',clearFilters); $('#find-path').addEventListener('click',findPath); $('#play-btn').addEventListener('click',playTimeline); $('#pause-btn').addEventListener('click',pauseTimeline); $('#new-btn').addEventListener('click',openEntry); $('#dialog-close').addEventListener('click',()=>$('#entry-dialog').close()); $('#entry-type').addEventListener('change',renderEntryFields); $('#entry-form').addEventListener('submit',saveEntry); $('#export-btn').addEventListener('click',exportJSON); $('#import-input').addEventListener('change',importJSON); document.querySelectorAll('[data-degree]').forEach(b=>b.addEventListener('click',()=>{degree=+b.dataset.degree; renderAll();})); }

// GRAPH
function allEntities(){return ['person','event','organization','location','source'].flatMap(type=>db[typeInfo[type][2]].map(item=>({...item,entityType:type,name:item.name||item.title})));}
function getEntity(id){return allEntities().find(x=>x.id===id)}
function entityDate(e){return e.startDate||e.date||e.founded||e.birthDate||''}
function filters(){return {types:[...document.querySelectorAll('#type-filters input:checked')].map(x=>x.value), relations:[...document.querySelectorAll('#relation-filters input:checked')].map(x=>x.value), start:$('#start-date').value, end:$('#end-date').value}}
function visibleData(){const f=filters();let rel=db.relationships.filter(r=>(!f.relations.length||f.relations.includes(r.type))&&(!f.start||r.startDate>=f.start)&&(!f.end||r.startDate<=f.end)&&(!animationYear||r.startDate.slice(0,4)<=animationYear));let ids=new Set(rel.flatMap(r=>[r.source,r.target]));if(selectedId){const allowed=neighbourhood(selectedId,degree);ids=new Set([...ids].filter(id=>allowed.has(id)));rel=rel.filter(r=>ids.has(r.source)&&ids.has(r.target));}const entities=allEntities().filter(e=>f.types.includes(e.entityType)&&ids.has(e.id));return{entities,rel};}
function renderAll(){renderGraph();renderDetails();renderTimeline();}
function renderGraph(){const {entities,rel}=visibleData(), nodes=$('#nodes'), edges=$('#edges');nodes.innerHTML='';edges.querySelectorAll('g').forEach(x=>x.remove());$('#graph-count').textContent=`${entities.length} varlık · ${rel.length} ilişki`;rel.forEach(r=>{const a=getEntity(r.source),b=getEntity(r.target);if(!a||!b||!entities.some(e=>e.id===a.id)||!entities.some(e=>e.id===b.id))return;const active=selectedId&&(r.source===selectedId||r.target===selectedId)||pathIds.includes(r.source)&&pathIds.includes(r.target);const dim=selectedId&&!active;const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=`<line class="${active?'active ':''}${dim?'dim':''}" x1="${a.x}%" y1="${a.y}%" x2="${b.x}%" y2="${b.y}%" ${r.directed?'marker-end="url(#arrow)"':''}/><text class="${dim?'dim':''}" x="${(a.x+b.x)/2}%" y="${(a.y+b.y)/2}%">${esc(r.type)} · ${r.startDate.slice(0,4)}</text>`;g.addEventListener('click',()=>selectRelation(r));edges.append(g);});entities.forEach(e=>{const button=document.createElement('button');const connected=db.relationships.some(r=>(r.source===selectedId||r.target===selectedId)&&(r.source===e.id||r.target===e.id));button.className=`node ${e.entityType} ${selectedId===e.id?'selected':''} ${pathIds.includes(e.id)?'path':''} ${selectedId&&e.id!==selectedId&&!connected&&!pathIds.includes(e.id)?'dim':''}`;button.style.left=e.x+'%';button.style.top=e.y+'%';button.innerHTML=`<span class="symbol">${typeInfo[e.entityType][1]}</span><b>${esc(e.name)}</b><small>${typeInfo[e.entityType][0]}</small>`;button.title=e.description||e.name;button.addEventListener('click',()=>selectEntity(e.id));enableDrag(button,e);nodes.append(button);});}

// NODE EVENTS
function enableDrag(el,entity){let drag=null;el.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId);e.stopPropagation()});el.addEventListener('pointermove',e=>{if(!drag)return;const box=$('#graph').getBoundingClientRect();entity.x=Math.max(4,Math.min(96,(e.clientX-box.left)/box.width*100));entity.y=Math.max(5,Math.min(94,(e.clientY-box.top)/box.height*100));drag={x:e.clientX,y:e.clientY};saveDatabase();renderGraph()});el.addEventListener('pointerup',()=>drag=null);}
function selectEntity(id){selectedId=id;pathIds=[];$('#degree-controls').hidden=false;renderAll();}
function selectRelation(r){selectedId=null;pathIds=[r.source,r.target];$('#degree-controls').hidden=true;$('#details').innerHTML=`<h2>${esc(r.type)}</h2><dl class="detail-data"><dt>İlişki</dt><dd>${esc(getEntity(r.source)?.name)} → ${esc(getEntity(r.target)?.name)}</dd><dt>Tarih</dt><dd>${formatDate(r.startDate)}${r.endDate?' – '+formatDate(r.endDate):''}</dd><dt>Güven</dt><dd>${esc(r.confidence)}</dd><dt>Açıklama</dt><dd>${esc(r.description)}</dd></dl>`;renderGraph();}

// RELATIONSHIPS / FILTERS
function renderFilters(){const types=$('#type-filters'), rels=$('#relation-filters');types.innerHTML='';rels.innerHTML='';Object.entries(typeInfo).forEach(([id,[label]])=>types.insertAdjacentHTML('beforeend',`<label class="check"><input checked type="checkbox" value="${id}">${label}</label>`));[...new Set(db.relationships.map(r=>r.type))].forEach(t=>rels.insertAdjacentHTML('beforeend',`<label class="check"><input checked type="checkbox" value="${esc(t)}">${esc(t)}</label>`));document.querySelectorAll('.filters input').forEach(i=>i.addEventListener('change',renderAll));}
function clearFilters(){document.querySelectorAll('.filters input[type=checkbox]').forEach(i=>i.checked=true);$('#start-date').value='';$('#end-date').value='';animationYear=null;selectedId=null;pathIds=[];$('#degree-controls').hidden=true;renderAll();}
function neighbourhood(start,max){const seen=new Set([start]),q=[[start,0]];while(q.length){const[id,d]=q.shift();if(d===max)continue;db.relationships.forEach(r=>{if(r.source===id||r.target===id){const n=r.source===id?r.target:r.source;if(!seen.has(n)){seen.add(n);q.push([n,d+1])}}})}return seen}

// SEARCH
function renderSearch(){const q=$('#search').value.trim().toLocaleLowerCase('tr'),out=$('#search-results');if(!q){out.innerHTML='';return}const matches=allEntities().filter(e=>e.name.toLocaleLowerCase('tr').includes(q));out.innerHTML=matches.length?matches.map(e=>`<button data-id="${e.id}">${typeInfo[e.entityType][1]} ${esc(e.name)} <small>(${typeInfo[e.entityType][0]})</small></button>`).join(''):'<button>Sonuç bulunamadı</button>';out.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>{$('#search').value='';out.innerHTML='';selectEntity(b.dataset.id)}));}

// DETAILS PANEL
function renderDetails(){if(!selectedId){$('#details').innerHTML='<p>Bir kişi, olay veya ilişki seçin.</p>';return}const e=getEntity(selectedId),list=db.relationships.filter(r=>r.source===e.id||r.target===e.id);let fields=`<dt>Tür</dt><dd>${typeInfo[e.entityType][0]}</dd>`;if(e.birthDate)fields+=`<dt>Doğum</dt><dd>${formatDate(e.birthDate)}</dd>`;if(e.occupation)fields+=`<dt>Meslek</dt><dd>${esc(e.occupation)}</dd>`;if(e.startDate)fields+=`<dt>Tarih</dt><dd>${formatDate(e.startDate)}</dd>`;if(e.country)fields+=`<dt>Ülke</dt><dd>${esc(e.country)}</dd>`;if(e.founded)fields+=`<dt>Kuruluş</dt><dd>${formatDate(e.founded)}</dd>`;$('#details').innerHTML=`<h2>${esc(e.name)}</h2><dl class="detail-data">${fields}<dt>Açıklama</dt><dd>${esc(e.description||'—')}</dd></dl><h3>BAĞLANTILAR</h3><ul class="detail-list">${list.map(r=>{const other=getEntity(r.source===e.id?r.target:r.source);return `<li><button data-id="${other.id}">→ ${esc(other.name)}<small>${esc(r.type)} · ${formatDate(r.startDate)}</small></button></li>`}).join('')}</ul>`;$('#details').querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>selectEntity(b.dataset.id)));}

// PATH FINDING
function renderPathOptions(){const people=db.people;['#path-start','#path-end'].forEach((s,index)=>$(s).innerHTML=people.map((p,i)=>`<option value="${p.id}" ${i===(index?1:0)?'selected':''}>${esc(p.name)}</option>`).join(''));}
function findPath(){const start=$('#path-start').value,end=$('#path-end').value,queue=[[start]],seen=new Set([start]);let found=[];while(queue.length){const p=queue.shift(),last=p[p.length-1];if(last===end){found=p;break}db.relationships.forEach(r=>{if(r.source===last||r.target===last){const n=r.source===last?r.target:r.source;if(!seen.has(n)){seen.add(n);queue.push([...p,n])}}})}pathIds=found;selectedId=null;$('#degree-controls').hidden=true;$('#path-result').textContent=found.length?`Bağlantı zinciri: ${found.map(id=>getEntity(id).name).join(' → ')}`:'Bağlantı bulunamadı.';renderAll();}

// TIMELINE
function renderTimeline(){const track=$('#timeline-track');track.innerHTML='';const entries=[...db.events.map(e=>({...e,label:e.name,kind:'event',date:e.startDate})),...db.relationships.map(r=>({label:r.type,kind:'relation',date:r.startDate,id:r.id}))].filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date));if(!entries.length)return;const years=entries.map(e=>+e.date.slice(0,4)),min=Math.min(...years),max=Math.max(...years, min+1);$('#timeline-label').textContent=`${min} – ${max}${animationYear?' · gösterilen yıl: '+animationYear:''}`;entries.forEach(e=>{if(animationYear&&+e.date.slice(0,4)>animationYear)return;const m=document.createElement('button');m.className='marker '+e.kind;m.style.left=((+e.date.slice(0,4)-min)/(max-min)*100)+'%';m.textContent=`${e.date.slice(0,4)} ${e.label}`;m.addEventListener('click',()=>e.kind==='event'?selectEntity(e.id):selectRelation(db.relationships.find(r=>r.id===e.id)));track.append(m);});}
function playTimeline(){pauseTimeline();const years=[...new Set([...db.events.map(e=>+e.startDate.slice(0,4)),...db.relationships.map(r=>+r.startDate.slice(0,4))])].sort();let i=0;animationYear=String(years[i]);renderAll();animationTimer=setInterval(()=>{i++;if(i>=years.length){pauseTimeline();return}animationYear=String(years[i]);renderAll()},900)}function pauseTimeline(){if(animationTimer)clearInterval(animationTimer);animationTimer=null;}

// DATA ENTRY
function openEntry(){renderEntryFields();$('#entry-dialog').showModal()}function renderEntryFields(){const type=$('#entry-type').value,entities=allEntities();let html='<label>Ad / başlık<input required name="name"></label><label>Tarih<input name="date" type="date"></label><label>Açıklama<textarea name="description"></textarea></label>';if(type==='person')html+='<label>Doğum tarihi<input name="birthDate" type="date"></label><label>Meslek<input name="occupation"></label>';if(type==='event')html+='<label>Olay türü<input name="eventType" value="olay"></label><label>Yer<select name="locationId">'+db.locations.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')+'</select></label>';if(type==='organization')html+='<label>Yer<select name="locationId">'+db.locations.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')+'</select></label>';if(type==='location')html+='<label>Ülke<input name="country" value="Türkiye"></label>';if(type==='source')html+='<label>URL<input name="url" type="url"></label>';if(type==='relationship')html='<label>Kaynak<select name="source">'+entities.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')+'</select></label><label>Hedef<select name="target">'+entities.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')+'</select></label><label>İlişki türü<input required name="relationType"></label><label>Tarih<input required name="date" type="date"></label><label>Açıklama<textarea name="description"></textarea></label>';$('#entry-fields').innerHTML=html;}
function saveEntry(e){e.preventDefault();const f=new FormData(e.target),type=$('#entry-type').value,id=type+'_'+Date.now(),date=f.get('date')||'';if(type==='relationship')db.relationships.push({id,source:f.get('source'),target:f.get('target'),type:f.get('relationType'),startDate:date,endDate:null,description:f.get('description'),confidence:'medium',sources:[],directed:true});else{const item={id,name:f.get('name'),description:f.get('description'),x:42+Math.random()*16,y:42+Math.random()*16};if(type==='person')Object.assign(item,{birthDate:f.get('birthDate'),deathDate:null,occupation:f.get('occupation'),tags:[],sources:[]}),db.people.push(item);if(type==='event')Object.assign(item,{startDate:date,endDate:null,locationId:f.get('locationId'),type:f.get('eventType'),sources:[]}),db.events.push(item);if(type==='organization')Object.assign(item,{founded:date,closed:null,locationId:f.get('locationId'),sources:[]}),db.organizations.push(item);if(type==='location')Object.assign(item,{country:f.get('country'),latitude:null,longitude:null}),db.locations.push(item);if(type==='source')Object.assign(item,{title:item.name,date,type:'belge',url:f.get('url')}),db.sources.push(item)}saveDatabase();$('#entry-dialog').close();renderFilters();renderPathOptions();renderAll();}

// IMPORT / EXPORT
function exportJSON(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='iliski-haritasi.json';a.click();URL.revokeObjectURL(a.href)}function importJSON(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const imported=JSON.parse(r.result);if(['people','events','organizations','locations','sources','relationships'].every(k=>Array.isArray(imported[k]))){db=imported;selectedId=null;pathIds=[];saveDatabase();renderFilters();renderPathOptions();renderAll()}else alert('Geçerli ilişki haritası JSON verisi seçin.')}catch{alert('JSON dosyası okunamadı.')}};r.readAsText(file);e.target.value=''}

// LOCAL STORAGE
function loadDatabase(){try{return JSON.parse(localStorage.getItem('relationship-map-db'))||structuredClone(demoDatabase)}catch{return structuredClone(demoDatabase)}}function saveDatabase(){localStorage.setItem('relationship-map-db',JSON.stringify(db))}function formatDate(d){return d?new Intl.DateTimeFormat('tr-TR').format(new Date(d)):'—'}
