import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { Download, Upload, Plus, Search, Play, Pause, ChevronRight, X, Moon, Sun, Route, Sparkles } from 'lucide-react';
import { demoData } from './data';
import { Entity, EntityType, GraphData, Relation } from './types';
import './styles.css';

const icons:Record<EntityType,string>={kişi:'●',olay:'◆',kurum:'■',yer:'▲',belge:'▣'};
const labels:Record<EntityType,string>={kişi:'Kişiler',olay:'Olaylar',kurum:'Kurumlar',yer:'Yerler',belge:'Belgeler'};
const fmt=(d?:string)=>d?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(new Date(d)):'—';
function shortest(data:GraphData,a:string,b:string){ const q=[[a]], seen=new Set([a]); while(q.length){const path=q.shift()!,last=path.at(-1)!;if(last===b)return path; data.relations.forEach(r=>{if(r.source===last||r.target===last){const n=r.source===last?r.target:r.source;if(!seen.has(n)){seen.add(n);q.push([...path,n])}}})}return [] }
function App(){
 const [data,setData]=useState<GraphData>(()=>JSON.parse(localStorage.getItem('relation-map')||'null')||demoData);
 const [selected,setSelected]=useState<string>('p1'),[query,setQuery]=useState(''),[dark,setDark]=useState(true),[playing,setPlaying]=useState(false),[year,setYear]=useState(2024),[types,setTypes]=useState<EntityType[]>(['kişi','olay','kurum','yer','belge']),[relationTypes,setRelationTypes]=useState<string[]>([]),[minDate,setMinDate]=useState('2020-01-01'),[maxDate,setMaxDate]=useState('2025-12-31'),[pathStart,setPathStart]=useState('p1'),[pathEnd,setPathEnd]=useState('p4'),[path,setPath]=useState<string[]>([]),[modal,setModal]=useState<'entity'|'relation'|null>(null),[story,setStory]=useState(false),[storyStep,setStoryStep]=useState(0),[pan,setPan]=useState({x:0,y:0,scale:1}),drag=useRef<{id?:string;x:number;y:number}>({});
 useEffect(()=>localStorage.setItem('relation-map',JSON.stringify(data)),[data]); useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setYear(y=>y>=2024?2020:y+1),1100);return()=>clearInterval(t)},[playing]);
 const allTypes=useMemo(()=>[...new Set(data.relations.map(r=>r.type))], [data]);
 const filtered=useMemo(()=>{const relations=data.relations.filter(r=>types.includes(data.entities.find(e=>e.id===r.source)?.type!)&&types.includes(data.entities.find(e=>e.id===r.target)?.type!)&&(!relationTypes.length||relationTypes.includes(r.type))&&r.date>=minDate&&r.date<=maxDate&&r.date.slice(0,4)<=String(year)); const ids=new Set(relations.flatMap(r=>[r.source,r.target]));return {relations,entities:data.entities.filter(e=>types.includes(e.type)&&(ids.has(e.id)||e.id===selected))}},[data,types,relationTypes,minDate,maxDate,year,selected]);
 const entity=data.entities.find(e=>e.id===selected); const connections=data.relations.filter(r=>r.source===selected||r.target===selected); const results=query?data.entities.filter(e=>e.name.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase())):[];
 const toggleType=(t:EntityType)=>setTypes(x=>x.includes(t)?x.filter(i=>i!==t):[...x,t]); const toggleRel=(t:string)=>setRelationTypes(x=>x.includes(t)?x.filter(i=>i!==t):[...x,t]);
 const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='iliski-haritasi.json';a.click()};
 const importFile=(f:File)=>{const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(String(rd.result));if(Array.isArray(d.entities)&&Array.isArray(d.relations))setData(d);else alert('Geçerli bir harita JSON dosyası seçin.')}catch{alert('JSON dosyası okunamadı.')}};rd.readAsText(f)};
 const nodeStyle=(e:Entity)=>({left:`${e.x}%`,top:`${e.y}%`});
 return <main className="app"><header><div className="brand"><span className="brandmark">◈</span><div><b>BAĞLANTI</b><small>İLİŞKİ HARİTASI</small></div></div><div className="search"><Search size={17}/><input aria-label="Haritada ara" placeholder="Kişi, olay veya kurum ara..." value={query} onChange={e=>setQuery(e.target.value)}/>{results.length>0&&<div className="results">{results.map(r=><button key={r.id} onClick={()=>{setSelected(r.id);setQuery('')}}><span className={'dot '+r.type}>{icons[r.type]}</span><span>{r.name}<small>{labels[r.type]}</small></span></button>)}</div>}</div><div className="header-actions"><button className="icon" onClick={()=>setDark(!dark)} aria-label="Tema değiştir">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="outline" onClick={download}><Download size={16}/> Dışa aktar</button><label className="icon" title="JSON içe aktar"><Upload size={17}/><input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label><button className="primary" onClick={()=>setModal('entity')}><Plus size={17}/> Yeni ekle</button></div></header>
 <section className="workspace"><aside className="filters"><div className="panel-heading"><span>FİLTRELER</span><button onClick={()=>{setTypes(['kişi','olay','kurum','yer','belge']);setRelationTypes([]);setMinDate('2020-01-01');setMaxDate('2025-12-31')}}>Sıfırla</button></div><Filter title="Varlık türleri">{(Object.keys(labels) as EntityType[]).map(t=><Check key={t} text={labels[t]} checked={types.includes(t)} onChange={()=>toggleType(t)} dot={t}/>)}</Filter><Filter title="İlişki türleri">{allTypes.slice(0,7).map(t=><Check key={t} text={t} checked={!relationTypes.length||relationTypes.includes(t)} onChange={()=>toggleRel(t)}/>)}</Filter><Filter title="Tarih aralığı"><div className="date-row"><input type="date" value={minDate} onChange={e=>setMinDate(e.target.value)}/><span>—</span><input type="date" value={maxDate} onChange={e=>setMaxDate(e.target.value)}/></div></Filter><Filter title="Görünüm"><Check text="Seçili bağlantıları öne çıkar" checked={!!selected} onChange={()=>setSelected(selected?'':'p1')}/><Check text="Düşük güveni gizle" checked={false} onChange={()=>{}}/><Check text="Doğrudan bağlantılar" checked={false} onChange={()=>{}}/></Filter></aside>
 <section className="center"><div className="graph-top"><div><span className="eyebrow">CANLI AĞ</span><b>{filtered.entities.length} varlık · {filtered.relations.length} ilişki</b></div><div className="legend">{(Object.keys(labels) as EntityType[]).map(t=><span key={t}><i className={t}>{icons[t]}</i>{labels[t]}</span>)}</div></div><div className="graph" onWheel={e=>{e.preventDefault();setPan(p=>({...p,scale:Math.min(1.6,Math.max(.65,p.scale-e.deltaY*.001))}))}} onPointerDown={e=>drag.current={x:e.clientX,y:e.clientY}} onPointerMove={e=>{if(drag.current.id){const item=data.entities.find(x=>x.id===drag.current.id)!;setData(d=>({...d,entities:d.entities.map(x=>x.id===item.id?{...x,x:Math.max(4,Math.min(96,x.x+(e.clientX-drag.current.x!)/5)),y:Math.max(6,Math.min(93,x.y+(e.clientY-drag.current.y!)/4))}:x)}));drag.current={id:item.id,x:e.clientX,y:e.clientY}}}} onPointerUp={()=>drag.current={}}><div className="canvas" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${pan.scale})`}}><svg>{filtered.relations.map(r=>{const a=data.entities.find(e=>e.id===r.source)!,b=data.entities.find(e=>e.id===r.target)!;const active=path.includes(r.source)&&path.includes(r.target), dim=selected&&!connections.some(c=>c.id===r.id)&&!active;return <g key={r.id} className={(active?'active ':'')+(dim?'dim':'')}><line x1={a.x+'%'} y1={a.y+'%'} x2={b.x+'%'} y2={b.y+'%'} markerEnd="url(#arrow)"/><text x={(a.x+b.x)/2+'%'} y={(a.y+b.y)/2+'%'}>{r.type} · {r.date.slice(0,4)}</text></g>})}<defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="currentColor"/></marker></defs></svg>{filtered.entities.map(e=>{const isPath=path.includes(e.id), dim=selected&&e.id!==selected&&!connections.some(r=>r.source===e.id||r.target===e.id)&&!isPath;return <button title={`${e.name} — ${e.description}`} onPointerDown={ev=>{ev.stopPropagation();drag.current={id:e.id,x:ev.clientX,y:ev.clientY}}} onClick={()=>setSelected(e.id)} onDoubleClick={()=>setSelected(e.id)} className={`node ${e.type} ${selected===e.id?'selected':''} ${isPath?'path':''} ${dim?'dim':''}`} style={nodeStyle(e)} key={e.id}><span>{icons[e.type]}</span><b>{e.name}</b><small>{e.detail?.split(' · ')[0]}</small></button>})}</div><div className="graph-help">Sürükle · Kaydırarak yakınlaştır · Düğüm detayları için seç</div></div><PathFinder entities={data.entities} start={pathStart} end={pathEnd} setStart={setPathStart} setEnd={setPathEnd} onFind={()=>setPath(shortest(data,pathStart,pathEnd))} path={path.map(id=>data.entities.find(e=>e.id===id)?.name||'')}/></section>
 <aside className="details">{entity?<><button className="close" onClick={()=>setSelected('')}><X size={18}/></button><div className="detail-icon"><span className={entity.type}>{icons[entity.type]}</span></div><span className="type-label">{labels[entity.type].slice(0,-2).toUpperCase()}</span><h2>{entity.name}</h2><p>{entity.detail}</p><p className="desc">{entity.description}</p><div className="stats"><div><b>{connections.length}</b><span>bağlantı</span></div><div><b>{connections.filter(r=>(data.entities.find(e=>e.id===(r.source===selected?r.target:r.source))?.type)==='olay').length}</b><span>olay</span></div><div><b>{entity.tags?.length||0}</b><span>etiket</span></div></div><h3>BAĞLANTILAR</h3><div className="connection-list">{connections.map(r=>{const o=data.entities.find(e=>e.id===(r.source===selected?r.target:r.source))!;return <button key={r.id} onClick={()=>setSelected(o.id)}><span className={'dot '+o.type}>{icons[o.type]}</span><span><b>{o.name}</b><small>{r.type} · {fmt(r.date)}</small></span><ChevronRight size={15}/></button>})}</div><button className="story-btn" onClick={()=>{setStory(true);setStoryStep(0)}}><Sparkles size={16}/> Hikâye modunda incele</button></>:<div className="empty"><Route/><h2>Bir düğüm seçin</h2><p>İlişkileri ve kaynakları keşfetmek için ağdaki herhangi bir varlığa tıklayın.</p></div>}</aside></section>
 <Timeline year={year} setYear={setYear} playing={playing} setPlaying={setPlaying}/>{modal&&<AddModal mode={modal} entities={data.entities} onClose={()=>setModal(null)} onAdd={item=>{if('source' in item)setData(d=>({...d,relations:[...d.relations,item as Relation]}));else setData(d=>({...d,entities:[...d.entities,item as Entity]}));setModal(null)}} onRelation={()=>setModal('relation')}/>} {story&&<Story path={path.length?path:shortest(data,'p1','p4')} entities={data.entities} step={storyStep} setStep={setStoryStep} close={()=>setStory(false)}/>}</main> }
const Filter=({title,children}:{title:string,children:ReactNode})=><div className="filter"><h3>{title}</h3>{children}</div>; const Check=({text,checked,onChange,dot}:{text:string,checked:boolean,onChange:()=>void,dot?:string})=><label className="check"><input type="checkbox" checked={checked} onChange={onChange}/>{dot&&<i className={dot}>{icons[dot as EntityType]}</i>}<span>{text}</span></label>;
function PathFinder({entities,start,end,setStart,setEnd,onFind,path}:{entities:Entity[],start:string,end:string,setStart:(x:string)=>void,setEnd:(x:string)=>void,onFind:()=>void,path:string[]}){return <div className="pathfinder"><Route size={17}/><b>Bağlantı yolunu bul</b><select value={start} onChange={e=>setStart(e.target.value)}>{entities.filter(x=>x.type==='kişi').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><span>→</span><select value={end} onChange={e=>setEnd(e.target.value)}>{entities.filter(x=>x.type==='kişi').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={onFind}>Bul</button>{path.length>0&&<small>{path.join(' → ')} <em>({path.length-1} adım)</em></small>}</div>}
function Timeline({year,setYear,playing,setPlaying}:{year:number,setYear:(n:number)=>void,playing:boolean,setPlaying:(b:boolean)=>void}){return <section className="timeline"><div><span className="eyebrow">ZAMAN ÇİZELGESİ</span><b>İlişkilerin zaman içindeki izleri</b></div><button className="play" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Duraklat':'Oynat'}</button><input aria-label="Yıl seçici" type="range" min="2020" max="2024" value={year} onChange={e=>setYear(+e.target.value)}/><div className="years">{[2020,2021,2022,2023,2024].map(y=><button className={y===year?'now':''} onClick={()=>setYear(y)} key={y}>{y}</button>)}</div></section>}
function AddModal({mode,entities,onClose,onAdd,onRelation}:{mode:'entity'|'relation',entities:Entity[],onClose:()=>void,onAdd:(x:Entity|Relation)=>void,onRelation:()=>void}){const [kind,setKind]=useState<EntityType>('kişi');const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(mode==='entity'){onAdd({id:'n'+Date.now(),name:String(f.get('name')),type:kind,date:String(f.get('date')),description:String(f.get('description')),detail:'Yeni demo kaydı',x:40+Math.random()*20,y:35+Math.random()*25})}else onAdd({id:'r'+Date.now(),source:String(f.get('source')),target:String(f.get('target')),type:String(f.get('type')),date:String(f.get('date')),description:String(f.get('description')),confidence:'Orta'})};return <div className="modal-back"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow">VERİ GİRİŞİ</span><h2>{mode==='entity'?'Yeni varlık ekle':'Yeni ilişki ekle'}</h2>{mode==='entity'?<><label>Varlık türü<select value={kind} onChange={e=>setKind(e.target.value as EntityType)}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Ad / başlık<input required name="name" placeholder="Örn. Yeni kişi"/></label></>:<><label>Kaynak<select name="source">{entities.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>İlişki türü<input required name="type" placeholder="Örn. katıldı"/></label><label>Hedef<select name="target">{entities.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label></>}<label>Tarih<input required type="date" name="date" defaultValue="2024-01-01"/></label><label>Açıklama<textarea name="description" placeholder="Bu kayda ilişkin açıklama..."/></label><button className="primary submit">{mode==='entity'?'VARLIĞI EKLE':'İLİŞKİYİ EKLE'}</button>{mode==='entity'&&<button type="button" className="link" onClick={onRelation}>Bunun yerine ilişki ekle</button>}</form></div>}
function Story({path,entities,step,setStep,close}:{path:string[],entities:Entity[],step:number,setStep:(n:number)=>void,close:()=>void}){const e=entities.find(x=>x.id===path[step]);return <div className="modal-back"><div className="story"><button className="close" onClick={close}><X/></button><span className="eyebrow">HİKÂYE MODU · {step+1}/{path.length}</span><h2>{e?.name}</h2><div className={'story-node '+e?.type}>{e&&icons[e.type]}</div><p>{e?.description}</p><div className="story-path">{path.map((id,i)=><i className={i<=step?'seen':''} key={id}/>)}</div><button className="primary submit" disabled={step===path.length-1} onClick={()=>setStep(step+1)}>Sonraki bağlantı <ChevronRight size={17}/></button></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
